all: test1 test2 test3 test4

test1: test1.cpp Ass4_3.cpp
	g++ -w -o mytest1 test1.cpp Ass4_3.cpp
test2: test2.cpp Ass4_3.cpp
	g++ -w -o mytest2 test2.cpp Ass4_3.cpp
test3: test3.cpp Ass4_3.cpp
	g++ -w -o mytest3 test3.cpp Ass4_3.cpp
test4: test4.cpp Ass4_3.cpp
	g++ -w -o mytest4 test4.cpp Ass4_3.cpp

clean:
	rm mytest1 mytest2 mytest3 mytest4